### ISSUE TITLE
"args" called in function main() in embeddings.py even though not defined

### ISSUE THREAD

**Issue by ute-hoffmann** [OATML-Markslab/ProteinNPT#21]
Running pipeline.sh with user-specific input throws this error: 

```
Traceback (most recent call last):
  File "/home/jupyter/ProteinNPT/scripts/pipeline.py", line 128, in <module>
    run_embeddings(
  File "/home/jupyter/ProteinNPT/scripts/embeddings.py", line 213, in main
    df = cleanup_ids_assay_data(df,indel_mode=args.indel_mode, target_seq=target_seq)
NameError: name 'args' is not defined
```

Deleting all occurrences of "args." in main() in embeddings.py solves the job

**Comment by pascalnotin** [comment]
Thank you!
